// C:\aquaticket\aquaticket-front\src\tools\generateSeatsSql.mjs
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

/**
 * 사용법(추천)
 * 1) 프로젝트 루트에서:
 *    node src/tools/generateSeatsSql.mjs
 *
 * 2) src/tools 폴더에서:
 *    node generateSeatsSql.mjs
 *
 * 옵션:
 *    node src/tools/generateSeatsSql.mjs --venue=2 --svg=src/assets/seatmap_demo.svg --out=src/tools/insert_seats.sql
 */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ✅ 스크립트 위치(src/tools) 기준으로 프로젝트 루트 고정
const projectRoot = path.resolve(__dirname, "..", "..");

function parseArgs(argv) {
  const out = {};
  for (const a of argv) {
    if (!a.startsWith("--")) continue;
    const [k, v = "true"] = a.slice(2).split("=");
    out[k.trim()] = v.trim();
  }
  return out;
}

const args = parseArgs(process.argv.slice(2));

// ✅ 기본값
const VENUE_ID = Number(args.venue ?? 2);
const svgRel = args.svg ?? "src/assets/seatmap_demo.svg";
const outRel = args.out ?? "src/tools/insert_seats.sql";

// ✅ 실제 경로(프로젝트 루트 기준)
const svgPath = path.resolve(projectRoot, svgRel);
const outPath = path.resolve(projectRoot, outRel);

if (!Number.isFinite(VENUE_ID) || VENUE_ID <= 0) {
  console.error("❌ --venue 값이 올바르지 않습니다. 예: --venue=2");
  process.exit(1);
}

if (!fs.existsSync(svgPath)) {
  console.error("❌ SVG 파일을 찾을 수 없습니다.");
  console.error("   찾는 경로:", svgPath);
  console.error("   힌트: --svg=src/assets/seatmap_demo.svg 처럼 프로젝트 루트 기준으로 지정하세요.");
  process.exit(1);
}

const svg = fs.readFileSync(svgPath, "utf8");

/**
 * seatmap_demo.svg는 대략 이런 형태:
 * <rect ... id="zone-standing-a-s1" x=".." y=".." data-zone-id="zone-standing-a" data-seat-no="1" />
 *
 * - data-zone-id, data-seat-no를 기준으로 seats 데이터 생성
 * - row_label은 y좌표를 정렬해서 A,B,C... 부여
 */

// rect 중 data-zone-id + data-seat-no 가진 것만 파싱
const seatRegex =
  /<rect\b[^>]*\bid="([^"]+)"[^>]*\bx="([^"]+)"[^>]*\by="([^"]+)"[^>]*\bdata-zone-id="([^"]+)"[^>]*\bdata-seat-no="([^"]+)"[^>]*>/g;

const rawSeats = [];
for (const m of svg.matchAll(seatRegex)) {
  const [, rectId, xStr, yStr, zoneId, seatNoStr] = m;
  const x = Number(xStr);
  const y = Number(yStr);
  const seatNo = Number(seatNoStr);

  if (!Number.isFinite(x) || !Number.isFinite(y) || !Number.isFinite(seatNo)) continue;

  rawSeats.push({
    rectId,
    zoneId,
    seatNo,
    x,
    y,
  });
}

if (rawSeats.length === 0) {
  console.error("❌ SVG에서 좌석(<rect data-seat-no=...>)을 찾지 못했습니다.");
  console.error("   seatRegex가 안 맞는 경우입니다. SVG에 data-seat-no, data-zone-id가 있는지 확인하세요.");
  process.exit(1);
}

// zone별로 y 값(unique) 정렬 → row_label(A,B,C...) 부여
const rowLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

const byZone = new Map();
for (const s of rawSeats) {
  if (!byZone.has(s.zoneId)) byZone.set(s.zoneId, []);
  byZone.get(s.zoneId).push(s);
}

const rowsApplied = [];

for (const [zoneId, list] of byZone.entries()) {
  // y 오름차순 정렬: 위→아래
  const ys = [...new Set(list.map((v) => v.y))].sort((a, b) => a - b);

  // y -> A,B,C...
  const yToRow = new Map();
  ys.forEach((y, idx) => {
    yToRow.set(y, rowLetters[idx] ?? String(idx + 1));
  });

  for (const s of list) {
    rowsApplied.push({
      venue_id: VENUE_ID,
      zone: zoneId,
      seat_no: s.seatNo,
      row_label: yToRow.get(s.y),
    });
  }
}

// 정렬(옵션): zone, row_label, seat_no
rowsApplied.sort((a, b) => {
  if (a.zone !== b.zone) return a.zone.localeCompare(b.zone);
  if (a.row_label !== b.row_label) return String(a.row_label).localeCompare(String(b.row_label));
  return a.seat_no - b.seat_no;
});

// SQL 생성
let sql = "";
sql += `-- GENERATED BY src/tools/generateSeatsSql.mjs\n`;
sql += `-- svg: ${svgRel}\n`;
sql += `-- venue_id: ${VENUE_ID}\n\n`;
sql += `START TRANSACTION;\n`;
sql += `DELETE FROM seats WHERE venue_id = ${VENUE_ID};\n\n`;
sql += `INSERT INTO seats (seat_no, row_label, zone, venue_id)\nVALUES\n`;

sql += rowsApplied
  .map((r, idx) => {
    const tail = idx === rowsApplied.length - 1 ? ";" : ",";
    // row_label이 undefined면 'A' 같은 기본값으로 막아줌(안전)
    const row = r.row_label ?? "A";
    return `(${r.seat_no}, '${row}', '${r.zone}', ${r.venue_id})${tail}`;
  })
  .join("\n");

sql += `\n\nCOMMIT;\n`;

// outPath 폴더 생성
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, sql, "utf8");

console.log("✅ insert_seats.sql 생성 완료");
console.log("   - SVG:", svgPath);
console.log("   - OUT:", outPath);
console.log("   - venue_id:", VENUE_ID);
console.log("   - 총 좌석 수:", rowsApplied.length);
